### PR TITLE
add a redundant loop condition to silence GCC warnings

### PR DESCRIPTION
**Pull request by oconnor663**
See:
https://github.com/BLAKE3-team/BLAKE3/issues/94
https://github.com/BLAKE3-team/BLAKE3/issues/183
https://github.com/BLAKE3-team/BLAKE3/issues/189

### CODE REVIEW

**Comment by oconnor663** [comment]
@fcorbelli can you confirm this change fixes the warnings on your system?

**Comment by fcorbelli** [comment]
If you refer to this
```
assert(num_cvs <= MAX_SIMD_DEGREE_OR_2);
```
no

**Comment by fcorbelli** [comment]
If you refer to this (first warning), yes
```
	  memcpy(&out+(parents_array_len * BLAKE3_OUT_LEN),
           &child_chaining_values+(2 * parents_array_len * BLAKE3_OUT_LEN),
           BLAKE3_OUT_LEN);
/*
    memcpy(&out[parents_array_len * BLAKE3_OUT_LEN],
           &child_chaining_values[2 * parents_array_len * BLAKE3_OUT_LEN],
           BLAKE3_OUT_LEN);
*/
```

**Comment by fcorbelli** [comment]
This one really need rewrite
```
 uint8_t out_array[MAX_SIMD_DEGREE_OR_2 * BLAKE3_OUT_LEN /*franzfix / 2*/];
  while (num_cvs > 2) {
    num_cvs =
        compress_parents_parallel(cv_array, num_cvs, key, flags, out_array);
    memcpy(cv_array, out_array, num_cvs * BLAKE3_OUT_LEN);
  }
  memcpy(out, cv_array, 2 * BLAKE3_OUT_LEN);
```
Unless you make a couple of malloc() and free(), or you have some reason to declare a MAX num_cvs.
The logic seems, to me, broken

**Comment by sneves** [comment]
@oconnor663  you can go [here](https://godbolt.org/z/P343Gfh8z) and cycle through every GCC version to check this out. Summary: your workaround works on every GCC version except 8.x. The following works everywhere:
```
while (num_cvs > 2 && num_cvs <= MAX_SIMD_DEGREE_OR_2)
```

**Comment by fcorbelli** [comment]
_already known max(num_cvs) and set an assert on this INTO THE LOOP_
If this is true (I do know how big can num_cvs become), then this make the same thing .

```
while (num_cvs > 2 && num_cvs <= MAX_SIMD_DEGREE_OR_2)
```

But I have a question: why cv_array can be bigger than out_array? Why simply do not declare two-same-sized-buffer ?

**Comment by oconnor663** [comment]
I've landed the version of this that Samuel suggested.

> why cv_array can be bigger than out_array

**Pull request merged**
