### PR TITLE
Replace movq by movd on MSVC assembly targets

### PR DESCRIPTION
**Pull request by sneves**

### CODE REVIEW

**Comment by OV2** [comment]
This breaks compiling in Studio 2017:
````
1>Assembling ..\..\..\BLAKE3\c\blake3_avx512_x86-64_windows_msvc.asm...
1>..\..\..\BLAKE3\c\blake3_avx512_x86-64_windows_msvc.asm(2424): error A2070: invalid instruction operands
1>..\..\..\BLAKE3\c\blake3_avx512_x86-64_windows_msvc.asm(2425): error A2070: invalid instruction operands
1>..\..\..\BLAKE3\c\blake3_avx512_x86-64_windows_msvc.asm(2519): error A2070: invalid instruction operands
1>..\..\..\BLAKE3\c\blake3_avx512_x86-64_windows_msvc.asm(2520): error A2070: invalid instruction operands
````
It seems the masm in this version wants the register operands with their doubleword variants (e.g. r9d). The old vmovq version worked.

Studio 2019 seems to accept both variants.

I was unable to compile it with Studio 2015. I don't think the masm version supplied with that has AVX512 support (it complains on `kmovw   k1, r9d` with `error A2008 : syntax error : k1`),

**Comment by sneves** [comment]
Is it only the AVX512 file that breaks?

**Comment by OV2** [comment]
Yes, that's the only one that throws errors in 2017.

**Comment by sneves** [comment]
This was fixed in 0359065018e2bafa31d319010ec5cebc35ad4393, FWIW.

**Comment by OV2** [comment]
Thanks!

**Pull request merged**
