### PR TITLE
Support running inside miri

### PR DESCRIPTION
**Pull request by ryoqun**
hi :)

As the title just says, this pr adds _minimal_ support for running under miri.

I wonder this pr could be merged without much hassle from me like enhancing ci... ;)

### CODE REVIEW

**Comment by oconnor663** [comment]
Thanks! I've followed up with 2435e29dbe57724ab3ae02fc5ea2a9cb83009f89 and d57818afdcf9715aafb1eaf30a34c6fffdb6eed0 to get `cargo +nightly miri test` working. It takes forever though, so I probably won't add it to CI :sweat_smile:

**Comment by oconnor663** [comment]
CI integration: 5b9af1c34746e20b4596c1812b683624bdcfc152

**Comment by ryoqun** [comment]
@oconnor663 hey, really thanks for polishing the miri support. now that it's minimally covered even by ci, i have to ask you: why not `1.5.1`? :) Thanks in advance.

**Comment by oconnor663** [comment]
Good call, done.

**Pull request merged**
