### PR TITLE
Add staticlib, callable from C

### PR DESCRIPTION
**Pull request by rurban**
See GH #8
(Untested but looks fine, maybe a C header file `blake3_rs.h` can be added also)

### CODE REVIEW

**Comment by elichai** [comment]
I'd replace the inputs with raw pointers (C) and at least asserts for nullness, or even return int like this: https://github.com/BLAKE2/BLAKE2/blob/ca4c89314abff54e3806b44e4a08164f8204f09a/sse/blake2sp.c#L78:L84

**Comment by oconnor663** [comment]
C bindings should probably expose the incremental API. But this is tricky, because the `Hasher` type is not currently `repr(C)`, and we don't want to force C to dynamically allocate it behind an opaque pointer. Maybe we could make it `repr(C)`? Or maybe it would make more sense to expose some more of the internal guts in a semi-stable way, by expanding https://github.com/BLAKE3-team/BLAKE3/blob/master/src/guts.rs.

**Comment by oconnor663** [comment]
I think the better approach here will be to just improve the C implementation to match the Rust one.

**Comment by cemeyer** [comment]
I like the idea of leaving the multithreaded, crypto-sensitive code in memory-safe rust and just linking the library as a build artifact from C code, but I can certainly see the appeal of a pure-C version as well. 
 So long as it has both feature parity and, uh, no bugs.

**Comment by oconnor663** [comment]
Note that there's a fair bit of unsafe code in the Rust version, mainly because using SIMD is inherently unsafe. It's possible that this could be reduced with some more abstractions, but at the same time there's a lot of value in being able to see exactly what intrinsics are used where, and I'm not eager to make the implementations more abstract.

**Comment by cemeyer** [comment]
Sure, that's reasonable.

**Comment by oconnor663** [comment]
The C implementation is now on par with the Rust implementation in terms of single-threaded performance. I'm going to close this for now.

**Pull request closed without merging**
