### PR TITLE
Adds BlockSizeUser trait fixes #224

### LINKED ISSUE #224: Hasher doesn't implement digest::crypto_common::BlockSizeUser
```rs
use hmac::{Mac, SimpleHmac};
use blake3::{Hasher};

fn main() {
   let mut x = SimpleHmac::<Hasher>::new_from_slice(b"test");
   x.update(b"test2");
   println!("{:?}", x.finalize().into_bytes());
}
```

```rs
error[E0599]: the function or associated item `new_from_slice` exists for struct `SimpleHmac<blake3::Hasher>`, but its trait bounds were not satisfied
  --> src/main.rs:5:38
   |
5  |    let mut x = SimpleHmac::<Hasher>::new_from_slice(b"test").unwrap();
   |                                      ^^^^^^^^^^^^^^ function or associated item cannot be called on `SimpleHmac<blake3::Hasher>` due to unsatisfied trait bounds
   |
  ::: /Users/joshuabrown3/.cargo/registry/src/github.com-1ecc6299db9ec823/hmac-0.12.0/src/simple.rs:14:1
   |
14 | pub struct SimpleHmac<D: Digest + BlockSizeUser> {
   | ------------------------------------------------
   | |
   | doesn't satisfy `SimpleHmac<blake3::Hasher>: FixedOutput`
   | doesn't satisfy `SimpleHmac<blake3::Hasher>: KeyInit`
   | doesn't satisfy `SimpleHmac<blake3::Hasher>: MacMarker`
   | doesn't satisfy `SimpleHmac<blake3::Hasher>: Mac`
   | doesn't satisfy `SimpleHmac<blake3::Hasher>: Sized`
   | doesn't satisfy `SimpleHmac<blake3::Hasher>: Update`
   |
   = note: the following trait bounds were not satisfied:
           `SimpleHmac<blake3::Hasher>: Sized`
           which is required by `SimpleHmac<blake3::Hasher>: Mac`
           `SimpleHmac<blake3::Hasher>: KeyInit`
           which is required by `SimpleHmac<blake3::Hasher>: Mac`
           `SimpleHmac<blake3::Hasher>: Update`
           which is required by `SimpleHmac<blake3::Hasher>: Mac`
           `SimpleHmac<blake3::Hasher>: FixedOutput`
           which is required by `SimpleHmac<blake3::Hasher>: Mac`
           `SimpleHmac<blake3::Hasher>: MacMarker`
           which is required by `SimpleHmac<blake3::Hasher>: Mac`
           `&SimpleHmac<blake3::Hasher>: KeyInit`
           which is required by `&SimpleHmac<blake3::Hasher>: Mac`
           `&SimpleHmac<blake3::Hasher>: Update`
           which is required by `&SimpleHmac<blake3::Hasher>: Mac`
           `&SimpleHmac<blake3::Hasher>: FixedOutput`
           which is required by `&SimpleHmac<blake3::Hasher>: Mac`
           `&SimpleHmac<blake3::Hasher>: MacMarker`
           which is required by `&SimpleHmac<blake3::Hasher>: Mac`
           `&mut SimpleHmac<blake3::Hasher>: KeyInit`
           which is required by `&mut SimpleHmac<blake3::Hasher>: Mac`
           `&mut SimpleHmac<blake3::Hasher>: Update`
           which is required by `&mut SimpleHmac<blake3::Hasher>: Mac`
           `&mut SimpleHmac<blake3::Hasher>: FixedOutput`
           which is required by `&mut SimpleHmac<blake3::Hasher>: Mac`
           `&mut SimpleHmac<blake3::Hasher>: MacMarker`
           which is required by `&mut SimpleHmac<blake3::Hasher>: Mac`


error[E0277]: the trait bound `blake3::Hasher: BlockSizeUser` is not satisfied
  --> src/main.rs:5:16
   |
5  |    let mut x = SimpleHmac::<Hasher>::new_from_slice(b"test").unwrap();
   |                ^^^^^^^^^^^^^^^^^^^^ the trait `BlockSizeUser` is not implemented for `blake3::Hasher`
   |
note: required by a bound in `SimpleHmac`
  --> /Users/joshuabrown3/.cargo/registry/src/github.com-1ecc6299db9ec823/hmac-0.12.0/src/simple.rs:14:35
   |
14 | pub struct SimpleHmac<D: Digest + BlockSizeUser> {
   |                                   ^^^^^^^^^^^^^ required by this bound in `SimpleHmac`
```

This is with 

```rs
[dependencies]
hmac = "0.12.0"
blake3 = { version = "1.3.0", features = ["traits-preview"] }
```

### PR DESCRIPTION
**Pull request by jbis9051**
Fixes #224

### CODE REVIEW

**Comment by oconnor663** [comment]
Could you help me follow what this enables? Do we get `SimpleHmac` working with this change?

**Comment by jbis9051** [comment]
@oconnor663 `SimpleHmac` works after this change. You can test it with the below.

```rs
// main.rs
use blake3::Hasher;
use hmac::{SimpleHmac, Mac};

fn main() {
   let mut x = SimpleHmac::<Hasher>::new_from_slice(b"test").unwrap();
   hmac::digest::Update::update(&mut x, b"test2");
   println!("{:?}", x.finalize().into_bytes());
}
// Cargo.toml
...
[dependencies]
hmac = "0.12.0"
blake3 = { git = "https://github.com/jbis9051/BLAKE3", features = ["traits-preview"] }
```

**Comment by oconnor663** [comment]
Could we add something like that as a `#[test]` inside of `src/traits.rs` as part of this PR?

**Comment by jbis9051** [comment]
@oconnor663  I'm attempting to add a test but having trouble running `cargo test`. 


I can open a new issue if needed.

`cargo build` run's fine but with `cargo test` I get (M1 Mac):


```
$ cargo test
   Compiling blake3 v1.3.0 (/Users/jbis/CLion/BLAKE3)
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-arch" "arm64" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.10o76td3j6n279i.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.1359srx1erp3or76.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.137x3n5x8chxk0v6.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.14zkj9xhqqczigvy.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.1683n9ijbnug6k6z.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.179mwi9tg9j4e1ll.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.17l6hczt3xfaw7v8.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.1b3w04s7mvh5vyzg.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.1br0dva2gnj5sl6h.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.1harcopr91zsbsf5.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.1ijj1uqnq13lreky.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.1kr5rxqgbpbni1af.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.1krbn3xkqb40latn.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.1mnuv1x2hg7itzcb.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.1of4jllzg1jtzuxs.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.1oy3ifk2sc3u2ath.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.1r7v3xl68za5tfph.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.1s2pcvn7jgnx6zhz.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.1tjuh8thpdu016zd.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.1vvxlaxab29zcd2m.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.1xqlctv60kpdbvq0.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.1z9wx5guqhvkblp9.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.20e1kophrvrxtum4.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.20sigzef1si4iuqx.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.22k2jngcvi6pjx0x.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.23k4zdw5x0zojvxk.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.24yz6byx8cxfn6v6.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.28jun0y8rc5br9de.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.28mf8ixqnwmqcqpg.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.2b7n8a9apu1snrv3.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.2bu97fui9bdomqug.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.2by6r0ebqa3nasvk.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.2fyeqbugwxwainsx.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.2gtqfi5rafve9v75.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.2iirhuw5co9rwzwl.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.2j5lu1vxdtr7jj5i.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.2knokllr70ocpgq8.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.2l5fpxrymq3sbnwn.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.2nu61urh14bl4wmf.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.2ofzclg6w6etfth2.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.2pv5s2of5hb4ebfi.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.2y0fl9tqw2xck9ee.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.2z1pwf164xgt466p.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.30g312tc5srct0tk.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.32i77dorbonc5zgk.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.34zh7w5ln8oqon5r.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.3904uur6ryf11kno.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.3dzecxpmza2yu463.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.3fk0o71agbiyy25.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.3hit8o89ek1khn0.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.3qdmvddoqggd2l98.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.3qrlikcyw0kk01se.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.3tug5myq9j450xy6.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.3wr22lumhl6oncoy.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.3z59nkalakhu1v0b.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.3zt63up7btr9kx4v.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.40g8qpf4l8tbj8h9.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.40o2swswg4apd5l8.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.41dvzzstoopx03xk.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.422we02v1wupr2af.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.42fnrv8n60mtaaoe.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.42jntqtv1iooillx.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.42tzmkcyhqxh7n98.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.47mrfrgu35tl8ieg.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.4aielt0fjry3smik.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.4dibbhi0si9u8xm0.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.4e7o9lyfk9yiucgy.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.4fk66p79u02pp3c6.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.4flta4hx2a5car2n.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.4gu898mhl2nivw8o.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.4iyrot6l5v7baf9g.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.4kof7is5p2c4p21y.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.4l6p4ontuuvvb0rz.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.4lj8aa5s6o76f5d8.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.4pvh7pivvqpzw6po.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.4pvv0rulelzuiha7.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.4rn6anmiu1scb3gv.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.4tyjt2egcscn62kj.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.4v62e4qlvpilt75n.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.4vk1ruliix375yoq.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.4wnscnemre2e7r0o.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.4x4rk3zo2tfrorri.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.50rmj4dptra32933.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.59eq44zdoor65mtl.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.5b9ojqdejt1ccmy8.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.5bphaxfg6oya8lu4.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.5bzh41f6qe8g948j.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.5i9qdesb65l74w2.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.78kbnq2ha3bgj9v.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.agq0xyxnjj2ufeq.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.d1uxo2jf43mzv1k.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.dlgptx82054rj3t.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.dq9etw2trhbv3o.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.e60df1e21p33g5v.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.fbb5ug816amay9o.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.itynvifsvus8hux.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.kqazzkc3uux2q2m.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.lkqiwcclug3xsyz.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.pl14nb2ms5q5hy1.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.qsjhzemoquduve9.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.r47605etzv3nzmb.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.sm7rukje1pghz17.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.xlg33m3x1q5ybh8.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.yplj75cer6dfdid.rcgu.o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607.hfod50cja3wp15m.rcgu.o" "-L" "/Users/jbis/CLion/BLAKE3/target/debug/deps" "-L" "/Users/jbis/CLion/BLAKE3/target/debug/build/blake3-1d934906add95643/out" "-L" "/Users/jbis/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "-Wl,-force_load" "-Wl,/Users/jbis/CLion/BLAKE3/target/debug/build/blake3-1d934906add95643/out/libblake3_neon.a" "/Users/jbis/CLion/BLAKE3/target/debug/deps/libconstant_time_eq-cbb8f6db35cff093.rlib" "/Users/jbis/CLion/BLAKE3/target/debug/deps/libreference_impl-33d4b27541fdf9e7.rlib" "/Users/jbis/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libtest-50b561a28eeca43a.rlib" "/Users/jbis/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libgetopts-f9f71a764fcb944d.rlib" "/Users/jbis/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libunicode_width-f12c81a19964b79d.rlib" "/Users/jbis/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_std-f11ec8942e9c3929.rlib" "/Users/jbis/CLion/BLAKE3/target/debug/deps/librand-11547683dc0e9900.rlib" "/Users/jbis/CLion/BLAKE3/target/debug/deps/librand_chacha-a0e061a4526ebc76.rlib" "/Users/jbis/CLion/BLAKE3/target/debug/deps/libppv_lite86-d9c4148da3dff8ae.rlib" "/Users/jbis/CLion/BLAKE3/target/debug/deps/librand_core-581158f2f03c675f.rlib" "/Users/jbis/CLion/BLAKE3/target/debug/deps/libgetrandom-468f1e326bca5a1f.rlib" "/Users/jbis/CLion/BLAKE3/target/debug/deps/liblibc-e25c363a0309cb50.rlib" "/Users/jbis/CLion/BLAKE3/target/debug/deps/libcfg_if-47c024ada37f49f5.rlib" "/Users/jbis/CLion/BLAKE3/target/debug/deps/libarrayvec-55c6e45c6cf929bf.rlib" "/Users/jbis/CLion/BLAKE3/target/debug/deps/libarrayref-31f595e172cde824.rlib" "/Users/jbis/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libstd-30760f0676b4a0cb.rlib" "/Users/jbis/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libpanic_unwind-128bf621675179b5.rlib" "/Users/jbis/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libobject-e3c2e7d06a0eb593.rlib" "/Users/jbis/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libmemchr-979ed69233e4feef.rlib" "/Users/jbis/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libaddr2line-31a996825442073f.rlib" "/Users/jbis/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libgimli-0a6b0aae1c45f58b.rlib" "/Users/jbis/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libstd_detect-3760f555626b9fdb.rlib" "/Users/jbis/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_demangle-025c156c0170bf7c.rlib" "/Users/jbis/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libhashbrown-9fb3325867b89a93.rlib" "/Users/jbis/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_alloc-53487701d347ed91.rlib" "/Users/jbis/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libunwind-619a2ff2f594bf80.rlib" "/Users/jbis/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcfg_if-8d4f06fae73533d8.rlib" "/Users/jbis/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/liblibc-0224867dea00ee30.rlib" "/Users/jbis/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/liballoc-7a08c2dd395a8174.rlib" "/Users/jbis/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_core-0d72239135eb113c.rlib" "/Users/jbis/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcore-64596866e8fcd459.rlib" "/Users/jbis/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-9fedd1ca092b15a8.rlib" "-liconv" "-lSystem" "-lresolv" "-lc" "-lm" "-liconv" "-L" "/Users/jbis/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "-o" "/Users/jbis/CLion/BLAKE3/target/debug/deps/blake3-679e6151e77c1607" "-Wl,-dead_strip" "-nodefaultlibs"
  = note: ld: warning: ignoring file /Users/jbis/CLion/BLAKE3/target/debug/build/blake3-1d934906add95643/out/libblake3_neon.a, building for macOS-arm64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )
          Undefined symbols for architecture arm64:
            "_blake3_hash_many_neon", referenced from:
                blake3::neon::hash_many::h801dabb94993de5e in blake3-679e6151e77c1607.1z9wx5guqhvkblp9.rcgu.o
                blake3::neon::hash_many::hcf486139bebba897 in blake3-679e6151e77c1607.1z9wx5guqhvkblp9.rcgu.o
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: could not compile `blake3` due to previous error
```

**Comment by oconnor663** [comment]
This warning is probably the underlying cause:

>  note: ld: warning: ignoring file /Users/jbis/CLion/BLAKE3/target/debug/build/blake3-1d934906add95643/out/libblake3_neon.a, building for macOS-arm64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )

Our `build.rs` file has compiled `blake3_neon.c` to provide the NEON implementation, but maybe it needs to supply some extra flag on the M1 to produce an object file in the correct format? I'm not sure, and unfortunately I don't have an M1 to test this with. 

As a workaround, you could use `--features=pure` to omit the NEON implementation entirely. But I'm guessing this is a real bug that'll affect other callers, so if you figure out how to fix it I'd love to know.

**Comment by jbis9051** [comment]
@oconnor663  Thanks. Added a test.

**Comment by oconnor663** [comment]
Awesome, I've landed this and added 540f708a94e1a50e20d6dbf6921a59560645f342 to assert the actual HMAC output bytes.

**Comment by jbis9051** [comment]
@oconnor663  Awesome thanks! When can we expect a release?

**Comment by oconnor663** [comment]
Just released v1.3.1.

**Pull request merged**
