### PR TITLE
Cargo.toml: update crypto-mac to 0.10.0

### PR DESCRIPTION
**Pull request by PaulGrandperrin**
This is an API breaking change

### CODE REVIEW

**Comment by oconnor663** [comment]
I've gone back and forth in the past about how properly to update `digest` and `crypto-mac` in the past:

- https://github.com/BLAKE3-team/BLAKE3/pull/90
- https://github.com/BLAKE3-team/BLAKE3/issues/122

We're thinking about tagging this crate 1.0 any day now, so this is going to become more important. I don't think anyone wants to bump the crate to 2.0 when `crypto-mac` gets to 0.11. What's the right arrangement here? @tarcieri?

**Comment by tarcieri** [comment]
@oconnor663 in the `signature` crate (which is post-1.0) we've opted to have a set of "unstable features" with `*-preview` names which depend on the pre-1.0 RustCrypto trait crates (e.g. `digest`):

https://docs.rs/signature/1.3.0/signature/#unstable-features

We explicitly call these out-of-scope for semver, but have a policy that we bump the *minor* version when the trait crates are updated.

It's sort of similar to having a 0.x crate for these features, but the other parts of the API are covered under a "1.0" semver guarantee.

**Comment by tarcieri** [comment]
Also note: we'll be releasing `crypto-mac` to v0.11 sometime in the next few weeks.  See: 

https://github.com/RustCrypto/traits/issues/392

**Comment by oconnor663** [comment]
The follow-up commit 07b746b1b4792f8885fe8749b22dd6242467b674 implements @tarcieri's suggestion, similar to the `digest` crate. (Though I don't think we'll make the nuanced guarantee about patch vs minor version bumps.)

**Comment by tarcieri** [comment]
Hopefully we'll be able to get to 1.0 sometime this year. Depends how quickly const generics evolve (we don't want to ship a 1.0 with `generic-array`)

**Pull request merged**
