### PR TITLE
add export_hasher and import_hasher to the guts module

### PR DESCRIPTION
**Pull request by oconnor663**
This was requested in https://github.com/BLAKE3-team/BLAKE3/issues/84.

### CODE REVIEW

**Comment by oconnor663** [comment]
This is an experimental PR. @That3Percent, if you have time to try this out for your use case, I'd love to get feedback.

**Comment by That3Percent** [comment]
Nice!

It will be at least a few days before I can have an end to end test. I reviewed the changes though and the API and functionality needed are confirmed by the unit tests, so I have every expectation that this will work great.

Cheers,
-Zac

**Comment by That3Percent** [comment]
We ended up going with a different solution that still uses Blake3 under the hood (especially for the XOF, which is great!). Instead of trying to transform all of the data into a contiguous byte stream and save and load hasher state (which was a pain because of the linear nature of hashes over byte streams compared to the nature of our problem) instead go with a solution that allowed us to treat all of the data as independent parts of a very large struct that can be hashed in parallel and combined piecewise.

You can read a little bit about what we're doing now here: [stable structured hash](https://www.reddit.com/r/crypto/comments/gjwmn4/please_break_my_stable_structured_hash_function/)

I feel really bad about you having implemented a thing we didn't use. Very sorry about that. It wasn't clear that this massively parallel solution was even possible until after.

**Comment by oconnor663** [comment]
No worries! This is an interesting experiment, and we can look back at this PR if we ever need it in the future.

> stable structured hash

Sounds complicated! :sweat_smile:

**Comment by iajoiner** [comment]
@oconnor663 Actually I have a use case for it.

**Pull request closed without merging**
